// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbsYhYH7lu19sShUvio48dblTu5aekCYs',
    appId: '1:783048189433:web:c6d9213ff3f687f43dc928',
    messagingSenderId: '783048189433',
    projectId: 'balance-131e6',
    authDomain: 'balance-131e6.firebaseapp.com',
    storageBucket: 'balance-131e6.firebasestorage.app',
    measurementId: 'G-J5G67BV1YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1g1E3iBhJ7cTRSc_wAoOqkrE9Yp9mWY',
    appId: '1:783048189433:android:bfbd8e06279347803dc928',
    messagingSenderId: '783048189433',
    projectId: 'balance-131e6',
    storageBucket: 'balance-131e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbVLARZyoFBEnHgd_G_EIWJOTLPpY2kY4',
    appId: '1:783048189433:ios:129f76c9126aa90d3dc928',
    messagingSenderId: '783048189433',
    projectId: 'balance-131e6',
    storageBucket: 'balance-131e6.firebasestorage.app',
    iosBundleId: 'com.example.homepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbVLARZyoFBEnHgd_G_EIWJOTLPpY2kY4',
    appId: '1:783048189433:ios:129f76c9126aa90d3dc928',
    messagingSenderId: '783048189433',
    projectId: 'balance-131e6',
    storageBucket: 'balance-131e6.firebasestorage.app',
    iosBundleId: 'com.example.homepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbsYhYH7lu19sShUvio48dblTu5aekCYs',
    appId: '1:783048189433:web:0c4ad8f71a5c6fc63dc928',
    messagingSenderId: '783048189433',
    projectId: 'balance-131e6',
    authDomain: 'balance-131e6.firebaseapp.com',
    storageBucket: 'balance-131e6.firebasestorage.app',
    measurementId: 'G-S15FEPGBGF',
  );
}


